cart/urls.py
from django.urls import path

from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

mystore/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from shop import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.product_list, name='product_list'),
    path('cart/', include('cart.urls', namespace='cart')),
    path('shop/', include('shop.urls', namespace='shop')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('users/', include('users.urls', namespace='users')),
    path('accounts/', include('allauth.urls')),

]

# for development purposes, not suitable for production
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

orders/urls.py
from django.urls import path
from . import views, ajax_view

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('ajax_payment/', views.ajax_payment, name='ajax_payment'),
    path('pay_with_paystack/', ajax_view.AjaxPayment.as_view(), name='pay_with_paystack'),
    path('<int:id>/pdf', views.Pdf.as_view(), name='render_pdf'),
]

orders/models.py
from django.db import models
from shop.models import Product
import random
import string
# Create your models here.


def random_code(digit=7, letter=3):
    sample_str = ''.join((random.choice(string.digits) for i in range(digit)))
    sample_str += ''.join((random.choice(string.ascii_uppercase) for i in range(letter)))

    sample_list = list(sample_str)
    final_string = ''.join(sample_list)
    return final_string


class Order(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    paid = models.BooleanField(default=False)
    reference_id = models.CharField(max_length=200, null=True, blank=True)
    order_id = models.CharField(default=random_code, max_length=10, null=True, blank=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'phone_number', 'city']

orders/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .models import OrderItem, Order
from .forms import OrderCreateForm
from cart.cart import Cart
# from .tasks import order_created

# views to render order report to pdf
from django.views.generic import View
from django.utils import timezone
from .render import Render


def order_create(request):
    cart = Cart(request)

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)

        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # clear the cart
            # cart.clear()
            # launch asynchronous task
            # order_created.delay(order.id)
            context = {
                'order': order,
                'cart': cart,
                'email': form.cleaned_data['email'],
                'phone': form.cleaned_data['phone_number']
            }
            return render(request, 'orders/pay_with_paystack.html', context)
    else:
        form = OrderCreateForm()
        return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})


def ajax_payment(request):
    # order_req = get_object_or_404(Order, order_id)
    if request.is_ajax():
        reference_id = request.POST.get('reference')
        x = Order(reference=reference_id, paid=True)
        x.save()
        if x:
            response = {
                'message': "Your Payment was successfully received"
            }
            return JsonResponse(response)
        else:
            response = {
                'message': "Your Payment Failed"
            }
            return JsonResponse(response)


# view for pdf rendering
class Pdf(View):

    def get(self, request, id):
        cart = Cart(request)
        order_item = get_object_or_404(Order, id=id)
        today = timezone.now()
        # clear the cart
        cart.clear()
        params = {
            'id': id,
            'today': today,
            'cart': cart,
            'order_item': order_item,
            # 'request': request
        }
        return Render.render('orders/order/pdf.html', params)

orders/templates/orders/pay_with_paystack.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}Payment With Paystack{% endblock %}

{% block content %}
    <div class='container' onload="payWithPaystack()">
        <div class='row justify-content-md-center'>
            <div class='col-md-auto'>
                <div id="output">

                </div>

                <div id="success">

                </div>

                <div id="display_info">
                    <p>Click <a href="{% url 'orders:render_pdf' order.id %}" target="_blank">Here</a> to print receipt of your purchase</p>
                    <p id="home">Go Back To Shop <a href="{% url 'shop:product_list' %}">Homepage</a></p>
                </div>
            </div>
        </div>
    </div>




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <script src="https://js.paystack.co/v1/inline.js"></script>
    <script>
        window.onload=function(){
            $("#display_info").hide();
            payWithPaystack();
        };

        function payWithPaystack(){
            var a = '{{ cart.get_total_price }}';
            var handler = PaystackPop.setup({
                key: 'pk_test_ce8979497f703eb955ab5ceb19fc54cdcb615e0d',
                email:'{{email}}',
                amount: parseInt(a) * 100,
                currency: "NGN",
                metadata: {
                    custom_fields: [
                        {
                            display_name: "Mobile Number",
                            variable_name: "mobile_number",
                            value: "{{phone}}",
                            order_id: "{{ order.id }}"
                        }
                    ]
                },

                callback: function(response){
                    var ref = response.reference;
                    var order_random_id = '{{ order.order_id }}'
                    var order_id = '{{ order.id }}'
                    //console.log(order_id)
                    
                    // $('div#home').show();
                    $.ajax({
                        method: "GET",
                        url: "{% url 'orders:pay_with_paystack' %}",
                        data: {
                            'id': order_id,
                          'reference': ref,
                        },
                        dataType: "json",

                        success: function (data) {
                            if (data.message == "Your Payment was successfully received") {
                                $('#output').html(data.message)
                                $('#success').html(`<p>Transaction reference is : <h2>${ref}</h2> and your order id is <h2>${order_random_id}</h2></p>`);
                                $("#display_info").show();
                            } else if (data.message == "Your Payment Failed!!!") {
                                $('#output').html(data.message)
                                $("#success").html(`<a href="{% url 'orders:order_create' %}" class="button">Checkout</a>`)
                            }
                        },
                    });
                },

                onClose: function(){
                    alert('window closed');
                }
            });

            handler.openIframe();
        }
    </script>
{% endblock content %}